### ISSUE TITLE
デモ用にあらかじめ数万ステップ学習しておいたノートブックを用意しておく

### ISSUE THREAD

**Issue by exoego** [antimon2/manabiya#11]
- [x] 別インスタンス作成
- [x] 多めに学習させておく（p3で）
- [x] 推論させた結果を表示したノートブックを保存しておく（推論で落ちることがあるのでp2で）

**Comment by antimon2** [comment]
学習データ追加待ち

**Comment by antimon2** [comment]
20k: https://nbviewer.jupyter.org/gist/antimon2/86d29d841d4ecd22d9232d2fa3799b4d
100k: https://nbviewer.jupyter.org/gist/antimon2/f0da6261cb145ac7b1692ee14b342311
